# NumPy Tutorial
numpy provides a high-performance multidimensional array object, and tools for working with these arrays.  
The core data structure is ndarray, often referred to as an array.

### Update NumPy to latest version

In [1]:
# Need to do this only once
! pip install numpy --upgrade

### Import libraries

In [2]:
# Import numpy library
import numpy as np

### numpy (1D) arrays

In [3]:
# Create a 1-dimensional (rank 1) array
a = np.array([1,6,4,6,2,4])

In [4]:
# Display datatype
type(a)

numpy.ndarray

In [5]:
# Display data structure shape
a.shape

(6,)

In [6]:
# Display array
a

array([1, 6, 4, 6, 2, 4])

In [7]:
# Reverse array
a[::-1]

array([4, 2, 6, 4, 6, 1])

In [8]:
# Print selected elements
print(a[1], a[4])

6 2


In [9]:
# Change an element of the array
a[0] = 9

# Print the updated array
print(a)

[9 6 4 6 2 4]


### numpy functions

In [10]:
print('min element in array is: ', np.min(a))
print('max element in array is: ', np.max(a))

min element in array is:  2
max element in array is:  9


In [11]:
print('sum of elements in array is: ', np.sum(a))
print('average of elements in array is: ', np.mean(a))
print('rounded average of elements in array is: ', np.round(np.mean(a),2))

sum of elements in array is:  31
average of elements in array is:  5.166666666666667
rounded average of elements in array is:  5.17


In [12]:
print('elements in array are: ', a)
print('sorted elements in array are: ', np.sort(a))
print('unique elements in array are: ', np.unique(a))

elements in array are:  [9 6 4 6 2 4]
sorted elements in array are:  [2 4 4 6 6 9]
unique elements in array are:  [2 4 6 9]


In [13]:
# Generate evenly spaced numbers within a specified interval
np.arange(5,25,5)

array([ 5, 10, 15, 20])

In [14]:
# Generate evenly spaced numbers over a specified interval
np.linspace(5,25,5)

array([ 5., 10., 15., 20., 25.])

### numpy (2D) arrays

In [15]:
# Create a 2-dimensional (rank 2) array
b = np.array([[1,2,3],[4,5,6]])

In [16]:
# Display datatype
type(b)

numpy.ndarray

In [17]:
# Display data structure shape
b.shape

(2, 3)

In [18]:
# Display array
b

array([[1, 2, 3],
       [4, 5, 6]])

In [19]:
# Change an element of the array
b[1,0] = 99

# Print the updated array
print(b)

[[ 1  2  3]
 [99  5  6]]


In [20]:
# Print selected elements
print(b[0, 0], b[1, 0])

1 99


In [21]:
# Create an array of all zeros
a = np.zeros((2,3))

# Display array
a

array([[0., 0., 0.],
       [0., 0., 0.]])

In [22]:
# Create a constant array
c = np.full((3,2), 7)

# Display array
c

array([[7, 7],
       [7, 7],
       [7, 7]])

### Array indexing (slicing)  
 https://www.w3schools.com/python/numpy/numpy_array_slicing.asp

Similar to Python lists, numpy arrays can be sliced. Since arrays may be multidimensional, you must specify a slice for each dimension of the array.

Slicing means taking elements from one given index to another given index.
- We pass slice instead of index like this: [start:end].
- We can also define the step, like this: [start:end:step].
- If we don't pass start its considered 0  
- If we don't pass end its considered length of array in that dimension
- If we don't pass step its considered 1

In [23]:
# Create a 4x5 array
d = np.array( [ [1,2,3,4,5], [6,7,8,9,10], [11,12,13,14,15], [16,17,18,19,20] ] )
d.shape     # Display shape

(4, 5)

In [24]:
d     # Display array

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [25]:
d[1,2] = 99     # Update array element
d               # Display updated array

array([[ 1,  2,  3,  4,  5],
       [ 6,  7, 99,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

#### (Positive) slicing

In [26]:
d[0:2, 3:5]

array([[ 4,  5],
       [ 9, 10]])

In [27]:
d[:2, 3:]

array([[ 4,  5],
       [ 9, 10]])

#### Negative slicing

In [28]:
d[1:3,2:4]

array([[99,  9],
       [13, 14]])

In [29]:
d[1:3,-3:-1]

array([[99,  9],
       [13, 14]])

In [30]:
d[-3:-1,-3:-1]

array([[99,  9],
       [13, 14]])

### Transpose array

In [31]:
# Create a 3x4 array
e = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
e

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [32]:
# Transpose array
e.T

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

### Reshape array
Reshaping means changing the shape of an array.  

In [33]:
e.reshape(4,3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

You are allowed to have one "unknown" dimension  
Pass -1 as the value, and NumPy will calculate this number for you

In [34]:
e.reshape(4,-1)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [35]:
e.reshape(2,-1)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])